#       _
#    __| | __ _  ___
#   / _` |/ _` |/ _ \
#  | (_| | (_| |  __/
#   \__,_|\__,_|\___|
# 
#  Copyright (C) 2023 @daeuniverse <https://github.com/daeuniverse>
# 
#  This is a open-source software, liscensed under the AGPL-3.0 License.
#  See /License for more information.

# Reference: https://github.com/marketplace/actions/rss-to-issues

name: Monitor new upstream git release versions

on:
  workflow_dispatch:
  schedule:
    # Run this Action every day at 4:00pm UTC
    - cron: "0 16 * * *"

env:
  CHARACTER_LIMIT: 1000
  MAX_AGE: 7d

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    strategy:
      matrix:
        include:
          - project: quic-go
            labels: quic-go/quic-go
            feed: https://github.com/quic-go/quic-go/releases.atom
      fail-fast: false
    steps:
      - uses: git-for-windows/rss-to-issues@v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          feed: ${{ matrix.feed }}
          prefix: "[New ${{ matrix.project }} version]"
          character-limit: ${{ env.CHARACTER_LIMIT }}
          dry-run: true
          max-age: ${{ env.MAX_AGE }}
          labels: github/release,automated-issue,${{ matrix.labels }}
